server:
  port: 7502

v1API:  /hambaam-gateway/resources

spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      default-filters:
        - RewritePath=${v1API}(?<segment>/?.*), $\{segment}
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: push-notification
          uri: http://push-notification-srv:8524
            #push-notification-srv
          predicates:
            - Path=${v1API}/api/push-notification/**
            - Method=POST,PUT
        #            - Header=Authorization, Basic [0-9a-zA-Z-.]*

        - id: check-version
          uri: http://check-version:8092
          predicates:
            - Path=${v1API}/check-version-api/resources/version/history/**
            - Method=GET

        - id: remote-config
          uri: http://remote-config-srv:8518
          predicates:
            - Path=${v1API}/remote-config/resources/**
            - Method=GET

        - id: car-toll
          uri: http://car-toll-api-srv:8514
          predicates:
            - Path=${v1API}/car-toll-api/resources/**
            - Method=GET,POST,PUT,DELETE

        - id: notice-api
          uri: http://notice-api-srv:8519
          predicates:
            - Path=${v1API}/notice-api/resources/**
            - Method=GET,POST,PUT


#        - id: openapi
#          uri: http://localhost:7502
#          predicates:
#            - Path=/v3/api-docs/**
#          filters:
#              - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

scopes:
  push-notification-secure: "customer-super"

permit:
  routes: "/hambaam-gateway/resources/remote-config/**;/hambaam-gateway/resources/check-version-api/**;/hambaam-gateway/resources/car-toll-api/**"


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway


#
#springdoc:
#  enable-native-support: true
#  api-docs:
#    groups:
#      enabled: true
#    enabled: true
#  group-configs:
#    - group: api-gateway
#      packages-to-scan:
#        - dev.kambei.apigateway
#      display-name: API Gateway
#    - group: notice-api
#      paths-to-match:
#        - /notice-api/**
#      display-name: notice api
#  swagger-ui:
#    config-url: /v3/api-docs/swagger-config
#    url: /v3/api-docs
#    urls:
#      - url: /v3/api-docs
#        name: API Gateway
#      - url: /notice-api/v3/api-docs
#        name: notice api
#
################################__SSO
#bmi.oauth2.excluded-urls: /swagger-ui/**:*,
#  /v3/api-docs/**:*,
#  /notice-api/api.html:*,
#  /notice-api/v3/api-docs:*,
#  /api.html:*,
#  /v3/**:*,
#  /h2/**:*,
#  /swagger-ui.html:*,
#  /webjars/**:*,
#  /v2/**:*,
#  /swagger-resources/**:*,
#  /actuator/**:*,
#  /trace/**:*