neowallet:
  base-url: http://172.30.42.70:8002

db:
  url: jdbc:db2://192.168.97.134:50000/BMI_API
  username: db2inst1
  password: 123456
  default_schema: neo_wallet2

rabbitmq:
  username: admin
  password: aDMeEn

psp:
  base-url: http://185.203.161.9:8099
  merchant-id: "000000140331692"
  terminal-id: "24056544"
  return-url: "www.sample.com/returnedPage"
  tripleDesKey: "hFI5UOwh9PUDbItN4k8/AacrnC5nTrk2"

ipg:
  base-url: http://psp-payment-gateway-srv:9039

user-profile:
  base-url: http://neobaam-srv:8090