###############################__NOTICE_API_security__###############################

db:
  username: gshahrokhabadi
  password: zDeAKpNCUke1nAuZA0F4
  database: hamrahbaamDB
  port: 27017
  host: 172.30.43.94
  url: mongodb://172.30.43.94:27017/hamrahbaamDB

log:
  level: info

