###############################__NOTICE_API_JOB_security__###############################

log:
  level: info


notice-api:
  delete:
    path: http://192.168.53.73:7502/hambaam-gateway/resources/notice-api/resources/message/delete